# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musichistory_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_length',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_length',
            field=models.DurationField(),
        ),
    ]
