# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musichistory_api', '0002_auto_20170203_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='musichistory_api.Genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_length',
            field=models.DurationField(verbose_name='album length'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_length',
            field=models.DurationField(verbose_name='track length'),
        ),
    ]
